### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by vhp1360** [mahurtado/oracle2couchbase#1]
Hello,
I had study on NoSQL database and found Couchbase is better for my goal, thanks for your soft,
any way,
I tried to import data from oracle. I'm not familiar with JAVA programming.i used your sample code and apps
`java -cp ./oracle2couchbase.jar:./couchbase-java-client-2.2.2.jar:./couchbase-core-io-1.2.2.jar:./rxjava-1.0.15.jar:./ojdbc6.jar -DcbClusterAddress=CouchbaseTest -DcbBucketName=Test -DoraAddress=192.168.110.10 -DoraUser=Test -DoraPassword=Test123  -DoraService=HR -DoraTables=Employee com.oracle2couchbase.Loader` 
and I faced below exception:

> Apr 18, 2016 11:06:37 AM com.oracle2couchbase.Config <init>
> INFO: Configuration loaded: Config [cbClusterAddress=CouchbaseTest, cbBucketName=Test, cbBucketPassword=null, oraAddress=192.168.110.10, oraPort=1521, oraUser=Test, oraPassword=Test123, oraSid=null, oraService=HR, oraTables=Employee]
> Apr 18, 2016 11:06:37 AM com.oracle2couchbase.Connection getOracleConnection
> INFO: Oracle connection url: jdbc:oracle:thin:@192.168.110.10:1521/HR
> Apr 18, 2016 11:07:04 AM com.oracle2couchbase.Loader getTableInfo
> INFO: TABLE Employee
> Apr 18, 2016 11:07:04 AM com.oracle2couchbase.Loader getTableInfo
> INFO: Columns
> Apr 18, 2016 11:07:04 AM com.oracle2couchbase.Loader getTableInfo
> INFO: [Column [index=1, name=MODIFIEDBY, type=12], Column [index=2, name=CREATEDBY, type=12], Column [index=3, name=MODIFIEDAT, type=93], Column [index=4, name=CREATEDAT, type=93],  ... ]
> Apr 18, 2016 11:07:04 AM com.oracle2couchbase.Loader getTableInfo
> INFO: PK_Columns
> Apr 18, 2016 11:07:04 AM com.oracle2couchbase.Loader getTableInfo
> INFO: []
> Apr 18, 2016 11:07:04 AM com.couchbase.client.core.CouchbaseCore <init>
> INFO: CouchbaseEnvironment: {sslEnabled=false, sslKeystoreFile='null', sslKeystorePassword='null', queryEnabled=false, queryPort=8093, bootstrapHttpEnabled=true, bootstrapCarrierEnabled=true, bootstrapHttpDirectPort=8091, bootstrapHttpSslPort=18091, bootstrapCarrierDirectPort=11210, bootstrapCarrierSslPort=11207, ioPoolSize=6, computationPoolSize=6, responseBufferSize=16384, requestBufferSize=16384, kvServiceEndpoints=1, viewServiceEndpoints=1, queryServiceEndpoints=1, ioPool=NioEventLoopGroup, coreScheduler=CoreScheduler, eventBus=DefaultEventBus, packageNameAndVersion=couchbase-jvm-core/1.2.2 (git: 1.2.2-dirty), dcpEnabled=false, retryStrategy=BestEffort, maxRequestLifetime=75000, retryDelay=ExponentialDelay{growBy 1.0 MICROSECONDS; lower=100, upper=100000}, reconnectDelay=ExponentialDelay{growBy 1.0 MILLISECONDS; lower=32, upper=4096}, observeIntervalDelay=ExponentialDelay{growBy 1.0 MICROSECONDS; lower=10, upper=100000}, keepAliveInterval=30000, autoreleaseAfter=2000, bufferPoolingEnabled=true, tcpNodelayEnabled=true, mutationTokensEnabled=false, socketConnectTimeout=1000, dcpConnectionBufferSize=20971520, dcpConnectionBufferAckThreshold=0.2, queryTimeout=75000, viewTimeout=75000, kvTimeout=2500, connectTimeout=5000, disconnectTimeout=25000, dnsSrvEnabled=false}
> Apr 18, 2016 11:07:07 AM com.couchbase.client.deps.io.netty.util.internal.ThreadLocalRandom getInitialSeedUniquifier
> _**WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?**_
> Apr 18, 2016 11:07:07 AM com.couchbase.client.core.node.CouchbaseNode$1 call
> INFO: Connected to Node CouchbaseTest
> Apr 18, 2016 11:07:08 AM com.couchbase.client.core.config.DefaultConfigurationProvider$8 call
> INFO: Opened bucket Test
> Apr 18, 2016 11:07:08 AM com.couchbase.client.core.node.CouchbaseNode$1 call
> INFO: Connected to Node 192.168.110.8
> Apr 18, 2016 11:07:08 AM com.couchbase.client.core.node.CouchbaseNode$1 call
> INFO: Connected to Node 192.168.110.18
> **_java.lang.NullPointerException
>     at com.oracle2couchbase.Loader.getJsonTypeObject(Loader.java:166)
>     at com.oracle2couchbase.Loader.getJson(Loader.java:139)
>     at com.oracle2couchbase.Loader.processTable(Loader.java:121)
>     at com.oracle2couchbase.Loader.main(Loader.java:45)_**

I know this is a sample code but as you know and mentioned in [your post](http://blog.couchbase.com/2016/february/moving-data-from-oracle-to-couchbase) this is most popular customer question,
could you please assist?
warm regards.

**Comment by mahurtado** [comment]
Thank you for your comment. This has been fixed in version 1.1

**Comment by SiphokaziManana** [comment]
Hi, I've downloaded the latest version and I'm getting the same error. It's still a NullPointerException in the getJsonTypeObject method. Specifically line 169

**Comment by mahurtado** [comment]
Hello, your issue has been solved in version 1.2
